sudo: required

services:
  - docker
  - mongodb

before_install:
  - docker pull minio/minio
  - mkdir -p /tmp/minio/testbucket # testbucket created on start
  - docker run -d  -p 9000:9000 -v "/tmp/minio/:/minio/"  -e "MINIO_ACCESS_KEY=DEVMINIOACCESSKEY" -e "MINIO_SECRET_KEY=DEVMINIOSECRET"  minio/minio server /minio
  - docker ps -a

language: java
jdk:
  - oraclejdk8
  
sudo: false

cache:
  directories:
   - $HOME/.m2

script:
  -mvn clean package

