sudo: required

services:
  - docker
  - mongodb

before_install:
- docker pull minio/minio
- docker run -d -p 9000:9000 minio/minio server /tmp/
- docker ps -a

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  
sudo: false

cache:
  directories:
   - $HOME/.m2

script: "mvn clean package"